name: navi_stream
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  dio: ^5.4.2+1
  injectable: ^2.3.5
  get_it: ^7.6.7
  retrofit: ^4.1.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  video_player: ^2.8.5
  mocktail: ^1.0.3
  flutter_screenutil: ^5.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.5.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/background_images/
  - assets/navistream_logo/
  - assets/bottom_navigation_bar_icons/
